version: '3.8'
services:
  fastify-app:
    #image: thongle153/blog:v1
    build: .
    volumes:
      - .:/src
      - /src/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file: .env
    networks:
      - app-networks
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-networks
networks:
  app-networks:
    driver: bridge
volumes:
  postgres_data: